[package]
name = "chdnbd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chd = "0.2.3"
nbd = "0.3.0"
